# --- Application Name ---
spring.application.name=auth-service

# --- Database Connection (Using the DB we just created) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate (Auto-creates tables for us) ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Server Port ---
# We change this to 8081 because 8080 is usually reserved for the Gateway
server.port=8081