server.port=8080
spring.application.name=api-gateway

# --- Disable Eureka (Stop the crash) ---
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# --- Route 1: Auth Service (Port 8081) ---
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# --- Route 2: Product Service (Port 8082) ---
spring.cloud.gateway.routes[1].id=product-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/products/**