# --- Application Name ---
spring.application.name=product-service

# --- Database Connection (Using product_db) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/product_db
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Server Port ---
# Auth is 8081, so Product will be 8082
server.port=8082

# --- Cloudinary Configuration ---
# REPLACE THESE WITH YOUR ACTUAL KEYS FROM CLOUDINARY DASHBOARD
cloudinary.cloud_name=dasgvyyms
cloudinary.api_key=316158935774126
cloudinary.api_secret=ZL6hWxm-y-XUnn9kz6zaaIAhJlk